import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { TestLabPage } from "./TestLabPage";
function jsonResponse(body: unknown): Response { return new Response(JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } }); }
function requestUrl(input: RequestInfo | URL): string { return typeof input === "string" ? input : input instanceof URL ? input.href : input.url; }
const image = () => new File([new Uint8Array([137, 80, 78, 71])], "error.png", { type: "image/png" });
it("runs one whole test with only file and question", async () => { const user = userEvent.setup(); const fetchMock = vi.fn<typeof fetch>(() => Promise.resolve(jsonResponse({ action: "preview", status: "validated" }))); vi.stubGlobal("fetch", fetchMock); render(<TestLabPage role="operator" csrfToken="csrf-value" />); await user.type(screen.getByLabelText("질문"), "이 이미지의 내용을 설명해줘"); await user.upload(screen.getByLabelText(/질문에 첨부할 이미지/), image()); const form = screen.getByRole("button", { name: "전체 파이프라인 시험" }).closest("form"); if (!form) throw new Error("form unavailable"); fireEvent.submit(form); expect(await screen.findByText(/validated/)).toBeInTheDocument(); const call = fetchMock.mock.calls.find(([input]) => requestUrl(input) === "/admin/v1/test-lab/preview"); const body = JSON.parse(String((call?.[1] as RequestInit).body)); expect(body.target_model).toBe("auto"); expect(body.conversion_profile).toBe("generic"); });
it("clears the result after its TTL", async () => { const user = userEvent.setup(); vi.stubGlobal("fetch", vi.fn<typeof fetch>(() => Promise.resolve(jsonResponse({ result: "TTL RESULT" })))); render(<TestLabPage role="operator" csrfToken="csrf-value" resultTtlMs={100} />); await user.type(screen.getByLabelText("질문"), "expire me"); await user.upload(screen.getByLabelText(/질문에 첨부할 이미지/), image()); const form = screen.getByRole("button", { name: "전체 파이프라인 시험" }).closest("form"); if (!form) throw new Error("form unavailable"); fireEvent.submit(form); expect(await screen.findByText(/TTL RESULT/)).toBeInTheDocument(); await waitFor(() => expect(screen.queryByText(/TTL RESULT/)).not.toBeInTheDocument(), { timeout: 1000 }); });
it("hides test controls from viewer", () => { render(<TestLabPage role="viewer" csrfToken="csrf-value" />); expect(screen.getByText(/viewer는 시험을 실행할 수 없습니다/)).toBeInTheDocument(); expect(screen.queryByLabelText(/질문에 첨부할 이미지/)).not.toBeInTheDocument(); });
