import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { TestLabPage } from "./TestLabPage";
function jsonResponse(body: unknown): Response { return new Response(JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } }); }
function requestUrl(input: RequestInfo | URL): string { return typeof input === "string" ? input : input instanceof URL ? input.href : input.url; }
const image = () => new File([new Uint8Array([137, 80, 78, 71])], "error.png", { type: "image/png" });
it("runs one whole test with a selected route, file, and question", async () => { const user = userEvent.setup(); const fetchMock = vi.fn<typeof fetch>((input) => requestUrl(input).endsWith("/routing-profiles") ? Promise.resolve(jsonResponse([{ id: "route-1", name: "기본 문서 분석", enabled: true }])) : Promise.resolve(jsonResponse({ action: "preview", status: "validated" }))); vi.stubGlobal("fetch", fetchMock); render(<TestLabPage role="operator" csrfToken="csrf-value" />); await user.selectOptions(await screen.findByLabelText("라우팅 프로필"), "route-1"); await user.type(screen.getByLabelText("질문"), "이 이미지의 내용을 설명해줘"); await user.upload(screen.getByLabelText(/질문에 첨부할 이미지/), image()); const form = screen.getByRole("button", { name: "전체 파이프라인 시험" }).closest("form"); if (!form) throw new Error("form unavailable"); fireEvent.submit(form); expect(await screen.findByText(/validated/)).toBeInTheDocument(); const call = fetchMock.mock.calls.find(([input]) => requestUrl(input) === "/admin/v1/test-lab/preview"); const body = JSON.parse(String((call?.[1] as RequestInit).body)); expect(body.routing_profile_id).toBe("route-1"); expect(body.target_model).toBe("auto"); });
it("clears the result after its TTL", async () => { const user = userEvent.setup(); vi.stubGlobal("fetch", vi.fn<typeof fetch>((input) => requestUrl(input).endsWith("/routing-profiles") ? Promise.resolve(jsonResponse([{ id: "route-1", name: "기본 문서 분석", enabled: true }])) : Promise.resolve(jsonResponse({ result: "TTL RESULT" })))); render(<TestLabPage role="operator" csrfToken="csrf-value" resultTtlMs={100} />); await user.selectOptions(await screen.findByLabelText("라우팅 프로필"), "route-1"); await user.type(screen.getByLabelText("질문"), "expire me"); await user.upload(screen.getByLabelText(/질문에 첨부할 이미지/), image()); const form = screen.getByRole("button", { name: "전체 파이프라인 시험" }).closest("form"); if (!form) throw new Error("form unavailable"); fireEvent.submit(form); expect(await screen.findByText(/TTL RESULT/)).toBeInTheDocument(); await waitFor(() => expect(screen.queryByText(/TTL RESULT/)).not.toBeInTheDocument(), { timeout: 1000 }); });
it("hides test controls from viewer", () => { render(<TestLabPage role="viewer" csrfToken="csrf-value" />); expect(screen.getByText(/viewer는 시험을 실행할 수 없습니다/)).toBeInTheDocument(); expect(screen.queryByLabelText(/질문에 첨부할 이미지/)).not.toBeInTheDocument(); });
it("runs the OmniRoute to Media Bridge whole flow without changing the existing test", async () => { const user = userEvent.setup(); const fetchMock = vi.fn<typeof fetch>((input) => requestUrl(input).endsWith("/routing-profiles") ? Promise.resolve(jsonResponse([{ id: "route-1", name: "기본 문서 분석", enabled: true }])) : Promise.resolve(jsonResponse({ id: "resp_1", output: [{ type: "message" }] }))); vi.stubGlobal("fetch", fetchMock); render(<TestLabPage role="operator" csrfToken="csrf-value" />); await user.selectOptions(await screen.findByLabelText("라우팅 프로필"), "route-1"); await user.type(screen.getByLabelText("질문"), "이 이미지의 내용을 설명해줘"); await user.upload(screen.getByLabelText(/질문에 첨부할 이미지/), image()); await user.type(screen.getByLabelText(/OmniRoute가 호출할 Media Bridge endpoint/), "https://media-bridge.sinsan.kr"); await user.type(screen.getByLabelText("OmniRoute API key"), "mbc_test_key"); fireEvent.submit(screen.getByRole("button", { name: "OmniRoute 전체 흐름 시험" }).closest("form")!); expect(await screen.findByText(/resp_1/)).toBeInTheDocument(); const call = fetchMock.mock.calls.find(([input]) => requestUrl(input) === "/admin/v1/test-lab/run"); const body = JSON.parse(String((call?.[1] as RequestInit).body)); expect(body.routing_profile_id).toBe("route-1"); expect(body.gateway_url).toBe("https://media-bridge.sinsan.kr"); expect(body.target_model).toBe("auto"); expect(body.execute_downstream).toBe(true); });
