services:
  media-bridge-db:
    restart: "no"
  media-bridge-control:
    image: media-bridge-control:test
    restart: "no"
    ports:
      - 127.0.0.1:${MEDIA_BRIDGE_TEST_CONTROL_PORT:-18081}:8081
  media-bridge-data:
    image: media-bridge-data:test
    restart: "no"
    ports:
      - 127.0.0.1:${MEDIA_BRIDGE_TEST_DATA_PORT:-18001}:8001

