import { useState, type SyntheticEvent } from "react";
import { adminRequest } from "../api/client";
import { SecretOnceDialog } from "../components/SecretOnceDialog";
import { safeItemPath, textField, type OperationsProps } from "./operationTypes";
import { useAdminList } from "./useAdminList";
interface CredentialResponse { credential: string; }
type Scope = "assets:write" | "mcp:invoke" | "responses:invoke";
const scopes: readonly { value: Scope; label: string }[] = [{ value: "assets:write", label: "Asset 업로드" }, { value: "mcp:invoke", label: "MCP 호출" }, { value: "responses:invoke", label: "Responses 실행" }];
export function CredentialsPage({ role, csrfToken }: OperationsProps) { const allowed = role === "admin"; const { items, failed, reload } = useAdminList(allowed ? "/credentials" : null); const [dialog, setDialog] = useState(false); const [name, setName] = useState(""); const [selectedScopes, setSelectedScopes] = useState<Scope[]>(["mcp:invoke"]); const [selected, setSelected] = useState<string[]>([]); const [credential, setCredential] = useState<string | null>(null); const [failedAction, setFailedAction] = useState(false); const writable = allowed && csrfToken !== null; if (!allowed) return <p role="alert">접근 키 관리는 관리자만 수행할 수 있습니다.</p>; const allSelected = !!items?.length && selected.length === items.length;
  function openCreate() { setDialog(true); setName(""); setSelectedScopes(["mcp:invoke"]); setFailedAction(false); } function toggleScope(scope: Scope, checked: boolean) { setSelectedScopes((current) => checked ? [...current, scope].filter((v, i, a) => a.indexOf(v) === i) : current.filter((v) => v !== scope)); }
  async function submit(e: SyntheticEvent<HTMLFormElement>) { e.preventDefault(); if (!writable || !selectedScopes.length) return; try { const orderedScopes = scopes.filter((scope) => selectedScopes.includes(scope.value)).map((scope) => scope.value); const result = await adminRequest<CredentialResponse>("/credentials", { method: "POST", csrfToken, body: { name, scopes: orderedScopes } }); setCredential(result.credential); setDialog(false); await reload(); } catch { setFailedAction(true); } }
  async function revokeSelected() { if (!writable || !selected.length || !window.confirm("선택한 접근 키를 폐기하시겠습니까?")) return; try { await Promise.all(selected.map((id) => adminRequest(safeItemPath("credentials", id), { method: "DELETE", csrfToken }))); setSelected([]); await reload(); } catch { setFailedAction(true); } }
  return <section aria-labelledby="credentials-title"><div className="page-heading"><div><h1 id="credentials-title">접근 키 관리</h1><p>발급된 원문은 한 번만 표시되며, 키 상태와 권한만 관리합니다.</p></div>{writable ? <button type="button" onClick={openCreate}>접근 키 발급</button> : null}</div>{failed ? <p role="alert">접근 키 목록을 불러올 수 없습니다.</p> : null}{failedAction ? <p role="alert">접근 키 작업을 완료하지 못했습니다.</p> : null}{items?.length === 0 && !failed ? <p role="status">발급된 접근 키가 없습니다.</p> : null}{items && items.length > 0 ? <>{selected.length ? <div className="inline-actions"><button type="button" className="danger-button" onClick={() => { void revokeSelected(); }}>선택 폐기 ({selected.length})</button></div> : null}<table><thead><tr><th><input aria-label="전체 접근 키 선택" type="checkbox" checked={allSelected} onChange={(e) => { setSelected(e.target.checked ? items.map((i) => textField(i, "selector")) : []); }} /></th><th>이름</th><th>Selector</th><th>상태</th></tr></thead><tbody>{items.map((item) => { const id = textField(item, "selector"); return <tr key={id}><td><input aria-label={`${textField(item, "name")} 선택`} type="checkbox" checked={selected.includes(id)} onChange={(e) => { setSelected((s) => e.target.checked ? [...s, id] : s.filter((v) => v !== id)); }} /></td><td>{textField(item, "name")}</td><td>{id}</td><td>{textField(item, "revoked_at") === "—" ? "활성" : "폐기"}</td></tr>; })}</tbody></table></> : null}{dialog ? <section className="dialog-backdrop" role="dialog" aria-modal="true" aria-labelledby="credential-dialog-title"><form className="dialog-card form-grid" onSubmit={(e) => { void submit(e); }}><h2 id="credential-dialog-title">접근 키 발급</h2><label htmlFor="operation-credential-name">접근 키 이름</label><input id="operation-credential-name" value={name} onChange={(e) => { setName(e.target.value); }} required /><fieldset><legend>권한</legend>{scopes.map((scope) => <label className="checkbox-row" key={scope.value}><input type="checkbox" checked={selectedScopes.includes(scope.value)} onChange={(e) => { toggleScope(scope.value, e.target.checked); }} /><span>{scope.label} ({scope.value})</span></label>)}</fieldset><div className="inline-actions"><button type="submit" disabled={!selectedScopes.length}>발급</button><button type="button" className="secondary-button" onClick={() => { setDialog(false); }}>취소</button></div></form></section> : null}{credential ? <SecretOnceDialog title="일회용 접근 키" values={[credential]} closeLabel="확인하고 닫기" onClose={() => { setCredential(null); void reload(); }} /> : null}</section>; }
